// Auto-generated by scripts/generate-build-info.js
export const buildInfo = {
  version: '0.1.529',
  commit: '25178931d3d762cda02729a873ab774c72e5071b',
  commitShort: '2517893',
  builtAt: '2025-12-05T15:42:08.820Z',
};
