// Auto-generated by scripts/generate-build-info.js
export const buildInfo = {
  version: '0.1.246',
  commit: '384d4116f88f931db834535d8ba2646bf8607b14',
  commitShort: '384d411',
  builtAt: '2025-11-17T15:24:07.504Z',
};
