// Auto-generated by scripts/generate-build-info.js
export const buildInfo = {
  version: '0.1.1262',
  commit: 'c73baca3bcca93a4139d08c4e8903e3214d1d090',
  commitShort: 'c73baca',
  builtAt: '2026-01-18T20:01:54.582Z',
};
