// Auto-generated by scripts/generate-build-info.js
export const buildInfo = {
  version: '0.1.1200',
  commit: '449567ecbeb2fdc016e9f8e1c2f91094678a885c',
  commitShort: '449567e',
  builtAt: '2026-01-08T21:46:56.622Z',
};
